# Generated by Django 5.2.15 on 2026-08-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_booking_reminder_1h_sent_booking_reminder_24h_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeddate',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockeddate',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
