# Generated by Django 5.2.14 on 2026-05-23 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emotional_state', models.TextField(blank=True, null=True)),
                ('primary_concern', models.TextField(blank=True, null=True)),
                ('support_preference', models.TextField(blank=True, null=True)),
                ('urgency', models.CharField(blank=True, max_length=20, null=True)),
                ('routing_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('resulting_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_source', to='core.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TriageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triage_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.triagesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
