# Generated by Django 5.2.14 on 2026-06-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0003_crisiskeyword_emergencycontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('AWAY', 'Away')], default='AWAY', max_length=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('counselor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accounts.graduatecounselor')),
            ],
            options={
                'verbose_name_plural': 'Counselor Availabilities',
            },
        ),
    ]
