# Generated by Django 5.2.15 on 2026-06-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_counseloravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('MATCHED', 'Matched'), ('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('ENDED', 'Ended')], default='WAITING', max_length=20),
        ),
    ]
