# Generated by Django 5.2.15 on 2026-06-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_session_reminder_1h_sent_session_reminder_24h_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='reminder_1h_sent',
        ),
        migrations.RemoveField(
            model_name='session',
            name='reminder_24h_sent',
        ),
    ]
