# Generated by Django 5.2.15 on 2026-06-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0006_remove_session_reminder_1h_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_requests_sent', to='accounts.graduatecounselor')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_requests_received', to='accounts.licensedtherapist')),
                ('triage_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_requests', to='core.triagesession')),
            ],
            options={
                'verbose_name': 'Escalation Request',
                'verbose_name_plural': 'Escalation Requests',
            },
        ),
    ]
