# Generated by Django 5.2.15 on 2026-06-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_escalationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escalationrequest',
            name='triage_session',
        ),
        migrations.AddField(
            model_name='escalationrequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalation_requests', to='core.session'),
        ),
    ]
