# Generated by Django 5.2.15 on 2026-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_graduatecounselor_background_check_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatecounselor',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='graduatecounselor',
            name='modalities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
