# Generated by Django 5.2.15 on 2026-08-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensedtherapist',
            name='session_duration',
            field=models.IntegerField(default=60),
        ),
    ]
