# Generated by Django 5.2.14 on 2026-05-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CRISIS', 'Crisis'), ('SUICIDE', 'Suicide Prevention'), ('DOMESTIC', 'Domestic Violence'), ('LGBTQ', 'LGBTQ+'), ('SUBSTANCE', 'Substance Abuse'), ('OTHER', 'Other')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Helpline Category',
                'verbose_name_plural': 'Helpline Categories',
            },
        ),
        migrations.CreateModel(
            name='HelplineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('is_24_7', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='helpline.helplinecategory')),
            ],
            options={
                'verbose_name': 'Helpline Entry',
                'verbose_name_plural': 'Helpline Entries',
            },
        ),
    ]
